<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MarkdownToPdf</AssemblyName>
    <RootNamespace>MarkdownToPdf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Adobe.PDF.Library.LM.NET" Version="18.*" />
  </ItemGroup>

</Project>
